# Brendon Phillips
# PhD Candidate
# Bauch computational epidemiology research group
# Department of Applied Mathematics
# Faculty of Mathematics
# Universiity of Waterloo

SNAPFOLDER = Snap-4.0

GLIB = $(SNAPFOLDER)/glib-core
SNAP = $(SNAPFOLDER)/snap-core
GLIBADV = $(SNAPFOLDER)/glib-adv
SNAPADV = $(SNAPFOLDER)/snap-adv
SNAPEXP = $(SNAPFOLDER)/snap-exp

CGLIB = $(GLIB)
CSNAP = $(SNAP)

UNAME := $(shell uname)

# Linux flags
CC = g++
CXXFLAGS += -Wall -fpermissive -Wfatal-errors -no-pie
CXXFLAGS += -O3 -msse2 -DNDEBUG -fopenmp
# turn on for crash debugging, get symbols with <prog> 2>&1 | c++filt
#CXXFLAGS += -g -rdynamic
#CXXFLAGS += -ggdb
# turn on for OpenMP
CXXOPENMP =
LDFLAGS +=
LIBS += -lrt
